version: '3.8'

services:

  web:
    image: nginx:1.22.1
    ports:
      - 80:80
    depends_on:
      - app
      - db
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build:
      dockerfile: ./docker/php/Dockerfile
      target: ${BUILD_TARGET:-application}
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: ${APP_ENV:-production}
      APP_DEBUG: ${APP_DEBUG:-false}
      DOCO_DB_HOST: ${DB_HOST}
      DOCO_DB_PORT: ${DB_PORT}
      DOCO_DB_DATABASE: ${DB_DATABASE}
      DOCO_DB_USERNAME: ${DB_USERNAME}
      DOCO_DB_PASSWORD: ${DB_PASSWORD}

  db:
    image: mysql:8.0.32
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: docker-fuel

volumes:
  mysqldata:
