version: '3.8'

services:

  web:
    build:
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - app
      - db

  app:
    build:
      dockerfile: ./docker/php/Dockerfile
      target: application
    environment:
      DOCO_DB_HOST: ${DB_HOST}
      DOCO_DB_PORT: ${DB_PORT}
      DOCO_DB_DATABASE: ${DB_DATABASE}
      DOCO_DB_USERNAME: ${DB_USERNAME}
      DOCO_DB_PASSWORD: ${DB_PASSWORD}

  db:
    image: mysql:8.0.32
    restart: unless-stopped #always
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: docker-fuel

volumes:
  mysqldata:
