version: '3.8'

services:

  web:
    build:
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build:
      dockerfile: ./docker/php/Dockerfile
      target: ${BUILD_TARGET:-application}
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: ${APP_ENV:-production}
      APP_DEBUG: ${APP_DEBUG:-false}

  db:
    ports:
      - 3306:3306
    restart: unless-stopped

volumes:
  mysqldata:
