version: '3.8'

services:

  web:
    image: hereismhtm/fuel-nginx:1.0
    ports:
      - 80:80
    depends_on:
      - app
      - db

  app:
    image: hereismhtm/fuel-php:1.1
    environment:
      DOCO_DB_HOST: ${DB_HOST}
      DOCO_DB_PORT: ${DB_PORT}
      DOCO_DB_DATABASE: ${DB_DATABASE}
      DOCO_DB_USERNAME: ${DB_USERNAME}
      DOCO_DB_PASSWORD: ${DB_PASSWORD}

  db:
    image: mysql:8.0.32
    restart: always
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}

volumes:
  mysqldata:
