version: '3.8'

services:

  web:
    image: hereismhtm/bb:fuel-web
    ports:
      - 80:80
    depends_on:
      - backend
      - db

  backend:
    image: hereismhtm/bb:fuel-backend
    volumes:
      - type: bind
        source: /var/local/log/fuel
        target: /var/www/html/storage/logs
    env_file: .env
    environment:
      DOCO_DB_HOST: ${DB_HOST}
      DOCO_DB_PORT: ${DB_PORT}
      DOCO_DB_DATABASE: ${DB_DATABASE}
      DOCO_DB_USERNAME: ${DB_USERNAME}
      DOCO_DB_PASSWORD: ${DB_PASSWORD}

  db:
    image: mysql:8.0.32
    restart: always
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}

volumes:
  mysqldata:
