version: '3.8'

services:
  web:
    #container_name: web-at-fuel
    build:
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - app
      - db

  app:
    #container_name: app-at-fuel
    build:
      dockerfile: ./docker/php/Dockerfile

  db:
    #container_name: db-at-fuel
    image: mysql:8.0.32
    restart: unless-stopped
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: docker-fuel

volumes:
  mysqldata:
