version: '3.8'

services:
  web:
    #container_name: web-at-fuel
    image: nginx:1.22.1
    ports:
      - 8000:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  app:
    #container_name: app-at-fuel
    build:
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www/html

  db:
    #container_name: db-at-fuel
    image: mysql:8.0.32
    ports:
      - 3306:3306
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: docker-fuel
    restart: unless-stopped

volumes:
  mysqldata:
